baseURL: ...
#не понимаю пока, что писать в шапке
name: Anonim Product 
code: Anonim
# код продукта
transaction rules: ANONIM_RULES
# код пакета правил обработки транзакций
как сослаться на другой файл и нужно ли? напишу пока условно так
transaction rules path: https://github.com/gasanova-ley/Product-Engine/blob/main/transaction_rules.yaml
limits: LIM_CODE
#код набора лимитов
limits path: 
Tarriff Plan: TARIFF_PLAN_CODE
# код тарифного плана
Tarriff Plan path: https://github.com/gasanova-ley/Product-Engine/blob/main/tariff_plans.yaml
Product Mechanic: MECHANIC_CODE
#логика работы продукта- бакеты (онлайн и оффлайн) и правила перехода средств между ними
Product Mechanic path: https://github.com/gasanova-ley/Product-Engine/blob/main/product_mechanics.yaml
FI: FI_CODE
# код финансового института
Entry Rules: ENTRY_RULE_PACK_CODE
# правила формирования проводок
Entry Rules path: https://github.com/gasanova-ley/Product-Engine/blob/main/entry_rules.yaml
FI: FI_CODE
# код финансового института
  
