baseURL: ...
#не понимаю пока, что писать в шапке
name: Anonim Product 
code: Anonim
transaction rules: TRANS_RULE_CODE
limits: LIM_CODE
Tarrif Plan: TARIFF_PLAN_CODE
Product Mechanic: MECHANIC_CODE
#логика работы продукта- бакеты (онлайн и оффлайн) и правила перехода средств между ними
FI: FI_CODE
  
