baseURL: ...
#не понимаю пока, что писать в шапке
name: Anonim Product 
code: Anonim
# код продукта
transaction rules: ANONIM_RULES
# код пакета правил обработки транзакций
как сослаться на другой файл и нужно ли? напишу пока условно так
transaction rules path:
limits: LIM_CODE
#код набора лимитов
Tarrif Plan: TARIFF_PLAN_CODE
# код тарифного плана
Product Mechanic: MECHANIC_CODE
#логика работы продукта- бакеты (онлайн и оффлайн) и правила перехода средств между ними
FI: FI_CODE
# код финансового института
  
